### ISSUE TITLE
Certificate Generator using jimp Node.js

### ISSUE THREAD

**Issue by mehra1812shivam** [harshgoel05/certify#10]
We want to print the values of the fields posted in JSON format in certificate template. Jimp is used here to print those values using the coordinates coming from those fields.
User uploads a certificate template with details and also enters the fields which he wants to get printed on the certificate. All these values are stored in a database in different collections.
While creating the certificate the id of the uploaded template and id when the user passed field values are passed in params in a get request to identify the correct template and the required field values.
After retrieving these values from the database they are looped to print each of them on the certificate.
**Bug:**
But after looping only the last field value is printed on the certificate template and rest our ignored.
Refer creating.js for this

Screenshot of the current output
![newcertificate2](https://user-images.githubusercontent.com/48999294/94792919-50108f00-03f7-11eb-9a7f-3c3f8b861c02.png)

**Comment by abhaybhatt** [comment]
@mehra1812shivam can i work on this?

**Comment by mehra1812shivam** [comment]
Yess i have assigned you the task.

**Comment by mehra1812shivam** [comment]
Reminder-You can work on it till 12 pm tomorrow .
